# Generated by Django 5.1 on 2024-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='events', to='base.ticket'),
        ),
    ]
