# Generated by Django 5.1 on 2024-09-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_event_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number_of_ticket',
            field=models.PositiveIntegerField(max_length=100, unique=True),
        ),
    ]
